### ISSUE TITLE
Is iemand geinteresseerd in een event als een abonnement wordt beeindigd door het IndicatieRegister?

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-generiek#10]
Het is denkbaar dat we abonnementen gaan verwijderen zonder dat daarvoor een aanvraag komt van buiten het IndicatieRegister.

Een voorbeeld is als een client overlijdt (oid). In dat geval zal (als er een abonnement op de client is), een event worden gestuurd voor het deleten van een client via de callback. 

In dat geval zullen we ook gelijk het abonnement verwijderen want er is geen garantie dat er een DELETE gaat komen die dit aanvraagt.

Is er een wens om voor het verwijderen van een abonnement ook een event te ontvangen?

Zo ja, dan zal wellicht de request body van de callback uitgebreid moeten worden.

**Comment by hilkojacobse** [comment]
Goed voorstel. Even kijken hoe we de body gaan uitbreiden. Hebben jullie een idee waar we dit kunnen positioneren?

**Comment by Joristdh** [comment]
Is het hier nodig om de request body uit te breiden? Zou een delete event zonder recordId of met als recordId het UUID van het abonnement niet al duidelijk genoeg zijn?

**Comment by rvanrest** [comment]
Abonnementen nog niet in scope. zie https://github.com/iStandaarden/iWlz_RequestForChange/issues/256
