### ISSUE TITLE
Kleine aanpassingen in schema

### ISSUE THREAD

**Issue by stefanbertensvecozo** [iStandaarden/iWlz-generiek#14]
Hoi Heren,

Zoals besproken nog even een samenvatting van een aantal bevindingen / vragen:

In alle types kunnen deze velden weg
`xOrgKey: Int! # Uniek ID van het netwerkpunt binnen het netwerk`
`xRequestID: String! # Identificatie van het request`

Bij `DeleteAbonnement` kan dit veld weg
`deletedAt: Time!`

Is `processAbonnement` omdat het zowel een create al een update ondersteund?
Of is `createAbonnement` wellicht een logischere naam?

Het returntype van `deleteAbonnement` is nu een `Abonnement`. Dit is onlogisch in onze ogen.
`deleteAbonnement(input: DeleteAbonnement!): Abonnement!`

**Comment by rvanrest** [comment]
@stefanbertensvecozo aanpassingen gecommit.
processAbonnement - createAbonnement

response deleteabonnement nu als Enum met toegestane waarden 204 en 404. als yaml versie.

**Comment by rvanrest** [comment]
voorlopig geen abonnementen ondersteuning
