### ISSUE TITLE
GraphQL enums naming convention

### ISSUE THREAD

**Issue by stefanbertensvecozo** [iStandaarden/iWlz-generiek#15]
Hoi Heren,

Als ik naar de specificaties bij GraphQL kijk maken ze van enum value's UPPER_SNAIL_CASE. Zie hieronder 2 artikelen daarover:
https://graphql.org/learn/schema/#enumeration-types
https://chillicream.com/docs/hotchocolate/defining-a-schema/enums#naming

Is het oké als wij deze naming convention overnemen?

**Comment by rvanrest** [comment]
Zeker! lijkt mij het enige juiste. dank voor de verwijzingen. 

Ik pas ze met #14 meteen aan.
