### ISSUE TITLE
recordID in schema api-specificatie/netwerkpunt.yaml

### ISSUE THREAD

**Issue by RinivanRasVecozo** [iStandaarden/iWlz-generiek#16]
Hoi Hilko en Remo,

In de schema van netwerkpunt/notificeren staat dat de recordID type is een string en als voorbeeld wordt deze url meegegeven "https://api.ciz.nl/wlzindicatieregister/wlzindicaties/da8ebd42-d29b-4508-8604-ae7d2c6bbddd". 

Van CIZ hebben we vernomen dat de recordID altijd gevuld zal worden met een uuid (id van de record en bij notificeren betreft het om de id van de indicatiebesluit). 

Willen jullie svp beoordelen of de schema aangepast moet worden naar type uuid en dat het voorbeeld in de schema dan ook mee aangepast wordt? Bedankt! 

Met vriendelijke groet,

Rini van Ras

**Comment by Jasperkroes** [comment]
Ik denk niet dat het handig is om het type van recordID aan te passen naar uuid, alleen maar omdat wij (CIZ) deze toevallig daarmee vullen. De specificaties zijn generiek en het kan dus zomaar zijn dat andere records, van ons of een ander register, geen uuids gebruiken als recordID.

Ik denk wel dat het een goed idee is om het voorbeeld aan te passen, maar dat moet in de andere specificaties ook gebeuren.

**Comment by rvanrest** [comment]
yaml specificatie is vervallen
