### ISSUE TITLE
Enum AbonnementType is niet CamelCase

### ISSUE THREAD

**Issue by sakirma** [iStandaarden/iWlz-generiek#18]
https://github.com/iStandaarden/iWlz-generiek/blob/10e6e227021efec7904174acf2044ea225fd7afe/gql-specificatie/netwerkpunt.graphql#L134

https://github.com/iStandaarden/iWlz-generiek/blob/10e6e227021efec7904174acf2044ea225fd7afe/gql-specificatie/netwerkpunt.graphql#L58

Het probleem dat ik zie is dat het type naar dit enum refereert als CamelCase. Terwijl het enum zonder CamelCase is gedefinieerd.

Wat ik verwacht is dat het enum `AbonnementType` wordt genoemd.

**Comment by rvanrest** [comment]
Voorlopig geen abonnementen
