### ISSUE TITLE
x-request-id ontbreekt in sommige calls / callbacks

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-generiek#2]
/volgindicaties/record heeft geen definitie voor header x-request`-id.

Dat geldt bijvoorbeeld ook voor de callback {/netwerkpunt/zendNotificatie}.

Er zijn waarschijnlijk nog meer plekken.

**Comment by hilkojacobse** [comment]
Aangepast op de 0.2.0 branch
