### ISSUE TITLE
Verschil tussen X-orgKey en organisatieId

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-generiek#3]
/backoffice/abonnement worden zowel X-orgKey als organisatieId gebruikt - lijkt dubbelop?

**Comment by hilkojacobse** [comment]
Het idee wat dat X-orgKey het netwerkpunt zou aanduiden. Theoretisch kunnen er meerdere organisaties achter een netwerkpunt schuil gaan.

**Comment by michielgkalkman** [comment]
Ok, het is denk ik wel een goed idee om in documentatie op te nemen dat het bij de X-orgKey gaat om een netwerkpunt want nu blijkt dat nergens uit. En ik neem aan dat het om het netwerkpunt gaat vanwaar de boodschap werd verstuurd en niet om het netwerkpunt dat de request doorgaf aan de backoffice?

Dit betekent dus ook dat als de beheerders van een register contact willen opnemen met de organisatie achter een request, we via het netwerkpunt uit de X-orgKey zullen moeten gaan (die het request doorspelen naar waar ze het request dan ook vandaan hebben gekregen). Is dat het idee?

Er staat trouwens ook niet in de swagger specs dat het bij organisatieId gaat om 1 van de organisaties achter het netwerkpunt van de X-orgKey - dus in principe zou dat ook een andere organisatie kunnen zijn. Ik neem aan dat "ons" netwerkpunt dat valideert en dat de backoffice dat niet hoeft te doen. Klopt dat?

**Comment by michielgkalkman** [comment]
Waarom moet de backoffice igv een notificatie een X-orgKey invullen? Lijkt mij iets voor het netwerkpunt dat deze notificatie doorzet?

**Comment by hilkojacobse** [comment]
Ik heb de overbodige x-orgKeys verwijderd op main.

**Comment by michielgkalkman** [comment]
Mooi, dank. Ik zou zelf misschien het woordje "zendende" toevoegen, dus "Uniek ID van de zendende organisatie binnen het netwerk".

Een aantal vragen die ik had gesteld, zijn nog niet beantwoord.
