### ISSUE TITLE
Request body /backoffice/abonnement

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-generiek#4]
Er zit een abonnementType in de request, dus waarom zitten er nog aparte organisatie, persoon en record ids in de request body?

Gewoon abonnementType, entiteitsId en entiteitsIdType lijkt dan wel voldoende.

**Comment by hilkojacobse** [comment]
Hi Michiel, 

zat ik zelf ook aan te denken, maar is in het overleg niet zo afgesproken. Wat voor enum zou je voorstellen voor entiteitsIdType?

Groet,

Hilko

**Comment by michielgkalkman** [comment]
EntiteitsIdType is dan afhankelijk van het abonnementsType, bijv.:

- organisatie is type "uzovi" (default)
- persoon is type "bsn" (default)
- record id is type "uuid" (default)

Vraag is dan even hoe we dit vastleggen - in eerste instantie zal het indicatieregister alleen abonnementen op organisatie ondersteunen. Hoe maken we dit duidelijk aan afnemers? Inclusief ons eigen netwerkpunt? Moet er misschien een soort metadata api komen die mogelijke entiteitstypes en abonnementstypes retourneert?

In het huidige schema is het mogelijk om een combinatie van abonnementen aan te maken - bijv abonnement op zowel een bepaalde organisatie als een bepaalde persoon. Mag ik aannemen dat we in een dergelijk geval dan een 400 gooien?

**Comment by hilkojacobse** [comment]
Ik ken afhankelijkheden wel in XSD's, maar weet eigenlijk niet of dat in openApi ook mogelijk is. Kun je eventueel een voorstel doen?

Als een ongeldige combinatie gevraagd wordt verwacht in inderdaad een 400 als response.

**Comment by rvanrest** [comment]
Voorlopig geen noodzaak voor abonnementen
