### ISSUE TITLE
0.2.0 Het lijkt er op dat de enum bij entiteit naar eventType moet

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-generiek#5]
eventType:
                    description: specificatie voor welke gebeurtenissen er een abonnement wordt afgesloten. all = alle gebeurtenissen / create = alleen aanmaken / update = alleen wijzigingen
                    type: string
entiteit:
                    description: entiteit waarop het abonnement geplaatst moet worden
                    type: string
                    enum: ["all","create", "update", "delete"]

Yup, de enum moet verplaatst worden

**Comment by hilkojacobse** [comment]
Aangepast in 0.2.0 banch
