### ISSUE TITLE
Verzenden notificatie vanuit Indicatieregister

### ISSUE THREAD

**Issue by ivovanopstal** [iStandaarden/iWlz-generiek#6]
In de Backoffice van het CIZ wordt bepaald voor welk Zorgkantoor een notificatie moet zijn. Echter wordt dit niet meegegeven in de notificatie richting het netwerkpunt. Hierdoor moet het netwerkpunt bijhouden welke abonnementen zijn afgesloten voor welke organisatie. Vervolgens moet het netwerkpunt de body van het notificatiebericht openen omdat alleen daarin het volgindicatienummer zit, ipv, in een header.

Beide issues kunnen voorkomen worden door in de header mee te geven voor welk zorgkantoor (Uzovi) (of andere netwerkpartij) de notificatie is.

**Comment by hilkojacobse** [comment]
Hi Ivo,

Dit werd door Stefanie ook opgemerkt. Ik heb hier een aanpassing voor doorgevoerd in de 0.2.0 branch.

Groet,

Hilko
