### ISSUE TITLE
Her en der wordt nog naar volgindicatie verwezen in main

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-generiek#8]

**Comment by michielgkalkman** [comment]
En waarom is commentaar soms in het engels?

**Comment by hilkojacobse** [comment]
Engelse comments zijn meegekomen met het template denk ik. Zal wel een keer een mooie vertaling maken.
Ik heb de laatste restjes volgindicatie eruit gehaald en gepust naar main.
