### ISSUE TITLE
Waarom zijn organisatieId en organisatieIdType verplicht?

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-generiek#9]
Zowel organisatieId als organisatieIdType zijn verplicht bij het creeeren van een abonnement.

Ik dacht dat was omdat we willen registreren welke organisatie achter het zendende NP het abonnement wilde aanvragen. 

Maar we geven dit organisatie id niet mee in de callback. Wordt de organisatie dan toch ergens in het netwerk bij het abonnement geregistreerd? In dat geval hoeven organisatieId en organisatieIdType wellicht niet verplicht te zijn.

**Comment by hilkojacobse** [comment]
Hi Michiel,

De organisatie die het abonnement plaatst wordt toch in de "backoffice" geregistreerd? Bij het versturen van de notificatie wordt het organisatieId en organisatieIdType WEL meegegeven. Ik zie echter dat deze ontbreken in de callback definitie, dat pas ik direct aan.
